wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: huggingface
    huggingface_version: 4.22.2
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.0
    start_time: 1680732787.24788
    t:
      1:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 79
      2:
      - 1
      - 9
      - 11
      - 41
      - 49
      - 55
      - 79
      3:
      - 23
      4: 3.9.0
      5: 0.14.0
      6: 4.22.2
      8:
      - 5
